/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#444748",
        "outline": "#747878",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-container": "#646464",
        "on-secondary-fixed": "#1b1b1b",
        "primary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#862200",
        "outline-variant": "#c4c7c8",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb5a0",
        "secondary": "#5e5e5e",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#ffffff",
        "primary": "#5d5f5f",
        "on-error": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "surface-container": "#eeeeee",
        "primary-container": "#ffffff",
        "surface-tint": "#5d5f5f",
        "on-tertiary-container": "#d93c01",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3131",
        "surface-bright": "#f9f9f9",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "background": "#f9f9f9",
        "secondary-container": "#e2e2e2",
        "on-tertiary-fixed": "#3b0900",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-fixed": "#ffdbd1",
        "on-surface": "#1a1c1c",
        "surface-container-low": "#f3f3f3",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#c6c6c7",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "on-primary-container": "#747676",
        "on-primary-fixed-variant": "#454747",
        "tertiary": "#b02f00", // Vibrant Orange Accent
        "on-secondary-fixed-variant": "#474747",
        "surface": "#f9f9f9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "section-gap": "128px",
        "gutter": "32px",
        "margin-mobile": "24px",
        "container-max": "1280px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "geist": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "mono": ["Source Code Pro", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-xl": ["80px", {"lineHeight": "1.1", "letterSpacing": "0.02em", "fontWeight": "800"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "headline-xl-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
};